layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: true
    forks: true

social_media:
  linkedin: austin-tran-57624a284/

topics:
  - name: Machine Learning
    image_url: https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/content/cover_image_file/cover_image/1304353/regular_1708x683_cover-0323-MachineLearning_Dan_Newsletter-b21703f41d807514083e297955e1b46d.png

  - name: Database Development
    image_url: https://www.trisotech.com/wp-content/uploads/oData-Header.jpg

  - name: Data Mining
    image_url: https://www.zuar.com/blog/content/images/size/w2000/2021/08/unnamed.png
  - name: Artificial Intelligence
    image_url: https://incubator.ucf.edu/wp-content/uploads/2023/07/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1-2048x1366.jpg
